language: node_js
node_js:
  - "stable"
before_install:
  - npm install -g surge
install:
  - npm install # make sure to install the deps when Travis runs.
after_success:
  - ./deploy.sh # TODO(you): deploy the PR changes to your staging server.
  - npm run lh -- modern-lamp.surge.sh